from enum import IntEnum


class OrderStatus(IntEnum):
    CREATED = 1
    COOKING = 2
    DELIVERING = 3
    COMPLETED = 4
    CANCELLED = 5


class OutboxEventType(IntEnum):
    ORDER_PAYMENT_CONFIRMED = 1
    ORDER_COOKING_STARTED = 2
    ORDER_READY_FOR_PICKUP = 3
    ORDER_COMPLETED = 4
    ORDER_CANCELLED = 5

    WALLET_BALANCE_CHARGED = 6
    CASHBACK_BALANCE_CREDITED = 7
    WALLET_FROZEN = 8

    WAREHOUSE_STOCK_DEPLETED = 9
    WAREHOUSE_RESTOCKED = 10
