from enum import IntEnum


class OrderStatus(IntEnum):
    CREATED = 1  # "CREATED"
    COOKING = 2  # "COOKING"
    DELIVERING = 3  # "DELIVERING"
    COMPLETED = 4  # "COMPLETED"
    CANCELLED = 5  # "CANCELLED"


class OutboxEventType(IntEnum):
    ORDER_PAYMENT_CONFIRMED = 1  # "ORDER_PAYMENT_CONFIRMED"
    ORDER_COOKING_STARTED = 2  # "ORDER_COOKING_STARTED"
    ORDER_READY_FOR_PICKUP = 3  # "ORDER_READY_FOR_PICKUP"
    ORDER_COMPLETED = 4  # "ORDER_COMPLETED"
    ORDER_CANCELLED = 5  # "ORDER_CANCELLED"

    WALLET_BALANCE_CHARGED = 6  # "WALLET_BALANCE_CHARGED"
    CASHBACK_BALANCE_CREDITED = 7  # "CASHBACK_BALANCE_CREDITED"
    WALLET_FROZEN = 8  # "WALLET_FROZEN"

    WAREHOUSE_STOCK_DEPLETED = 9  # "WAREHOUSE_STOCK_DEPLETED"
    WAREHOUSE_RESTOCKED = 10  # "WAREHOUSE_RESTOCKED"


class OutboxEventStatus(IntEnum):
    PENDING = 1  # "PENDING"
    COMPLETED = 2  # "COMPLETED"
    FAILED = 3  # "FAILED"
