import enum


class OrderStatus(enum.Enum):
    CREATED = "CREATED"
    COOKING = "COOKING"
    DELIVERING = "DELIVERING"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class OutboxEventType(enum.Enum):
    ORDER_PAYMENT_CONFIRMED = "ORDER_PAYMENT_CONFIRMED"
    ORDER_COOKING_STARTED = "ORDER_COOKING_STARTED"
    ORDER_READY_FOR_PICKUP = "ORDER_READY_FOR_PICKUP"
    ORDER_COMPLETED = "ORDER_COMPLETED"
    ORDER_CANCELLED = "ORDER_CANCELLED"

    WALLET_BALANCE_CHARGED = "WALLET_BALANCE_CHARGED"
    CASHBACK_BALANCE_CREDITED = "CASHBACK_BALANCE_CREDITED"
    WALLET_FROZEN = "WALLET_FROZEN"

    WAREHOUSE_STOCK_DEPLETED = "WAREHOUSE_STOCK_DEPLETED"
    WAREHOUSE_RESTOCKED = "WAREHOUSE_RESTOCKED"


class OutboxEventStatus(enum.Enum):
    PENDING = "PENDING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
