"""initial

Revision ID: bf939f29db61
Revises:
Create Date: 2026-07-23 19:52:40.668731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf939f29db61'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dishes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("(jsonb_typeof(info -> 'name') = 'string') AND (jsonb_typeof(info -> 'meta') = 'object') AND (jsonb_typeof(info -> 'origin_and_recipe') = 'object') AND (jsonb_typeof(info -> 'price_usd_minor_units') = 'number') AND ((info ->> 'price_usd_minor_units')::numeric % 1 = 0)", name='chk_dishes_root_structure_and_types'),
    sa.CheckConstraint("(length(info ->> 'name') BETWEEN 6 AND 67) AND (info ->> 'name' ~* 'burger')", name='chk_dishes_name_rules'),
    sa.CheckConstraint('\n        (info -> \'origin_and_recipe\' -> \'ingredients_weight_g\') IS NOT NULL AND\n        (jsonb_typeof(info -> \'origin_and_recipe\' -> \'ingredients_weight_g\') = \'object\') AND\n\n        NOT jsonb_path_exists(\n            info -> \'origin_and_recipe\' -> \'ingredients_weight_g\',\n            \'$.* ? (@.type() != "number" || @ < 0)\'\n        )\n    ', name='chk_dishes_dynamic_ingredients_weight_valid'),
    sa.CheckConstraint('\n        (jsonb_typeof(info -> \'meta\' -> \'weight_g\') = \'number\' AND (info -> \'meta\' -> \'weight_g\')::text::float > 0) AND\n        (jsonb_typeof(info -> \'meta\' -> \'is_vegan\') = \'boolean\') AND\n        (jsonb_typeof(info -> \'meta\' -> \'is_psyop\') = \'boolean\') AND\n\n        (jsonb_typeof(info -> \'meta\' -> \'macro\' -> \'calories\') = \'number\' AND (info -> \'meta\' -> \'macro\' ->> \'calories\')::float >= 0) AND\n        (jsonb_typeof(info -> \'meta\' -> \'macro\' -> \'proteins_g\') = \'number\' AND (info -> \'meta\' -> \'macro\' ->> \'proteins_g\')::float >= 0) AND\n        (jsonb_typeof(info -> \'meta\' -> \'macro\' -> \'fats_g\') = \'number\' AND (info -> \'meta\' -> \'macro\' ->> \'fats_g\')::float >= 0) AND\n        (jsonb_typeof(info -> \'meta\' -> \'macro\' -> \'carbs_g\') = \'number\' AND (info -> \'meta\' -> \'macro\' ->> \'carbs_g\')::float >= 0) AND\n\n        (jsonb_typeof(info -> \'meta\' -> \'micro_and_toxic\') = \'object\') AND\n        NOT jsonb_path_exists(\n            info -> \'meta\' -> \'micro_and_toxic\',\n            \'$.* ? (@.type() != "number" || @ < 0)\'\n        ) AND\n\n        (jsonb_typeof(info -> \'meta\' -> \'macro\' -> \'water_percentage\') = \'number\' AND\n        (info -> \'meta\' -> \'macro\' ->> \'water_percentage\')::float BETWEEN 0.0 AND 100.0)\n    ', name='chk_dishes_static_meta_metrics'),
    sa.CheckConstraint('\n        (length(info -> \'origin_and_recipe\' ->> \'origin_zone\') BETWEEN 10 AND 67) AND\n        (length(info -> \'origin_and_recipe\' ->> \'cooking_process\') BETWEEN 10 AND 1488) AND\n        (jsonb_typeof(info -> \'origin_and_recipe\' -> \'supply_chain\') = \'array\') AND\n\n        NOT jsonb_path_exists(\n            info -> \'origin_and_recipe\' -> \'supply_chain\',\n            \'$[*] ? (\n                @.merchant_name.type() != "string" ||\n                @.location.type() != "string" ||\n                @.trust_level.type() != "number" ||\n                !(@.merchant_name like_regex "^.{1,67}$") ||\n                !(@.location like_regex "^.{1,67}$") ||\n                @.trust_level < 0 ||\n                @.trust_level > 32767\n            )\'\n        )\n    ', name='chk_dishes_recipe_and_supply_chain_rules'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dishes_info_path_gin', 'dishes', ['info'], unique=False, postgresql_using='gin', postgresql_ops={'info': 'jsonb_path_ops'}, postgresql_where=sa.text('is_available IS true'), postgresql_with={'fastupdate': False})
    op.create_index('uq_dishes_name_lowercase', 'dishes', [sa.literal_column("lower(CAST(info ->> 'name' AS VARCHAR))")], unique=True, postgresql_where=sa.text('is_available IS true'))




    op.create_table('ingredients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_available', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_ingredients_name_lowercase', 'ingredients', [sa.literal_column('lower(name)')], unique=True, postgresql_where=sa.text('is_available IS true'))




    op.create_table('outbox_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_type', sa.SmallInteger(), nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )




    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )




    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('total_cost_usd', sa.BIGINT(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orders_user_active', 'orders', ['user_id'], unique=False, postgresql_where=sa.text('status IN (1, 2, 3)'))
    op.execute("ALTER TABLE orders SET (fillfactor = 88)")



    op.create_table('user_cards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('seti_id', sa.String(length=29), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_user_cards_seti_id', 'user_cards', ['seti_id'], unique=True)
    op.create_index('uq_user_cards_user_id', 'user_cards', ['user_id'], unique=True)




    op.create_table('wallet_top_ups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.BIGINT(), nullable=False),
    sa.Column('status', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_wallet_top_ups_user_idempotency')
    )
    op.create_index('idx_wallet_top_ups_cleanup', 'wallet_top_ups', ['created_at'], unique=False, postgresql_where=sa.text('status = 1'))
    op.execute("ALTER TABLE wallet_top_ups SET (fillfactor = 88)")



    op.create_table('wallets',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('balance', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('cashback_balance', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.execute("ALTER TABLE wallets SET (fillfactor = 76)")



    op.create_table('warehouse',
    sa.Column('ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('weight_g', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ingredient_id')
    )
    op.execute("ALTER TABLE warehouse SET (fillfactor = 67)")



    op.create_table('order_contents',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('dish_id', sa.Uuid(), nullable=False),
    sa.Column('price_usd', sa.Integer(), nullable=False),
    sa.Column('qty', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('order_id', 'dish_id')
    )
    op.execute("ALTER TABLE order_contents SET (fillfactor = 80)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_contents')
    op.drop_table('warehouse')
    op.drop_table('wallets')
    op.drop_index('idx_wallet_top_ups_cleanup', table_name='wallet_top_ups', postgresql_where=sa.text('status = 1'))
    op.drop_table('wallet_top_ups')
    op.drop_index('uq_user_cards_user_id', table_name='user_cards')
    op.drop_index('uq_user_cards_seti_id', table_name='user_cards')
    op.drop_table('user_cards')
    op.drop_index('idx_orders_user_active', table_name='orders', postgresql_where=sa.text('status IN (1, 2, 3)'))
    op.drop_table('orders')
    op.drop_table('users')
    op.drop_table('outbox_events')
    op.drop_index('uq_ingredients_name_lowercase', table_name='ingredients', postgresql_where=sa.text('is_available IS true'))
    op.drop_table('ingredients')
    op.drop_index('uq_dishes_name_lowercase', table_name='dishes', postgresql_where=sa.text('is_available IS true'))
    op.drop_index('idx_dishes_info_path_gin', table_name='dishes', postgresql_using='gin', postgresql_ops={'info': 'jsonb_path_ops'}, postgresql_where=sa.text('is_available IS true'), postgresql_with={'fastupdate': False})
    op.drop_table('dishes')
    # ### end Alembic commands ###
