[project]
name = "iwe"
version = "0.1.0"
description = "whatcha wanna know huh"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "asyncpg>=0.31.0",
    "uvloop>=0.22.1",
    "granian>=2.7.9",
    "alembic>=1.18.5",
    "fastapi>=0.139.0",
    "httpx>=0.28.1",
    "orjson>=3.11.9",
    "pydantic-settings>=2.14.2",
    "sqlalchemy[asyncio]>=2.0.51",
    "stripe>=15.3.0",
    "uuid6>=2025.0.1",
]

[build-system]
requires = ["uv-build"]
build-backend = "uv_build"
