"""initial

Revision ID: e714db4ac3ce
Revises:
Create Date: 2026-07-05 16:56:22.583895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e714db4ac3ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dishes',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('is_available', sa.Boolean(), nullable=False),
            sa.Column('info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
            sa.CheckConstraint("info ? 'name'", name='chk_dishes_info_must_define_name'),
            sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dishes_info_path_gin', 'dishes', ['info'], unique=False, postgresql_using='gin', postgresql_ops={'info': 'jsonb_path_ops'}, postgresql_where=sa.text("is_available IS true AND CAST((info ->> 'name') AS VARCHAR) IS NOT NULL"), postgresql_with={'fastupdate': False})
    op.create_index('uq_dishes_name_lowercase', 'dishes', [sa.literal_column("lower(CAST(info ->> 'name' AS VARCHAR))")], unique=True, postgresql_where=sa.text("is_available IS true AND CAST((info ->> 'name') AS VARCHAR) IS NOT NULL"))
    op.create_table('ingredients',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('name', sa.String(length=50), nullable=False),
            sa.Column('is_available', sa.Boolean(), nullable=False),
            sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_ingredients_name_lowercase', 'ingredients', [sa.literal_column('lower(name)')], unique=True, postgresql_where=sa.text('is_available IS true'))
    op.create_table('outbox_events',
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
            sa.Column('event_type', sa.SmallInteger(), nullable=False),
            sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), nullable=False),
            sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dish_ingredients',
            sa.Column('dish_id', sa.Uuid(), nullable=False),
            sa.Column('ingredient_id', sa.Uuid(), nullable=False),
            sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('dish_id', 'ingredient_id')
    )
    op.create_index('idx_dish_ingredient', 'dish_ingredients', ['ingredient_id'], unique=False)
    op.create_table('orders',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('user_id', sa.Uuid(), nullable=False),
            sa.Column('total_price', sa.BIGINT(), nullable=False),
            sa.Column('status', sa.SmallInteger(), nullable=False),
            sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
            sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orders_user_active', 'orders', ['user_id'], unique=False, postgresql_where=sa.text('status IN (1, 2, 3)'))
    op.create_table('wallet_top_ups',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('user_id', sa.Uuid(), nullable=False),
            sa.Column('amount', sa.BIGINT(), nullable=False),
            sa.Column('status', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
            sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wallet_top_ups_cleanup', 'wallet_top_ups', ['id'], unique=False, postgresql_where=sa.text('status = 1'))
    op.execute("ALTER TABLE wallet_top_ups SET (fillfactor = 88)")
    op.create_table('wallets',
            sa.Column('user_id', sa.Uuid(), nullable=False),
            sa.Column('balance', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
            sa.Column('cashback_balance', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
            sa.PrimaryKeyConstraint('user_id')
    )
    op.execute("ALTER TABLE wallets SET (fillfactor = 76)")
    op.create_table('warehouse',
            sa.Column('ingredient_id', sa.Uuid(), nullable=False),
            sa.Column('quantity', sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
            sa.PrimaryKeyConstraint('ingredient_id')
    )
    op.execute("ALTER TABLE warehouse SET (fillfactor = 67)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warehouse')
    op.drop_table('wallets')
    op.drop_index('idx_wallet_top_ups_cleanup', table_name='wallet_top_ups', postgresql_where=sa.text('status = 1'))
    op.drop_table('wallet_top_ups')
    op.drop_index('idx_orders_user_active', table_name='orders', postgresql_where=sa.text('status IN (1, 2, 3)'))
    op.drop_table('orders')
    op.drop_index('idx_dish_ingredient', table_name='dish_ingredients')
    op.drop_table('dish_ingredients')
    op.drop_table('users')
    op.drop_table('outbox_events')
    op.drop_index('uq_ingredients_name_lowercase', table_name='ingredients', postgresql_where=sa.text('is_available IS true'))
    op.drop_table('ingredients')
    op.drop_index('uq_dishes_name_lowercase', table_name='dishes', postgresql_where=sa.text("is_available IS true AND CAST((info ->> 'name') AS VARCHAR) IS NOT NULL"))
    op.drop_index('idx_dishes_info_path_gin', table_name='dishes', postgresql_using='gin', postgresql_ops={'info': 'jsonb_path_ops'}, postgresql_where=sa.text("is_available IS true AND CAST((info ->> 'name') AS VARCHAR) IS NOT NULL"), postgresql_with={'fastupdate': False})
    op.drop_table('dishes')
    # ### end Alembic commands ###
